
name: 'Create jira release notes'
description: 'A github action to create release notes'
author: 'randomizer<randil.fernando@outlook.com>'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  branch-diff-file:
    description: 'The branch diff file'
    required: true
  jira-project-key:
    description: 'The jira project key'
    required: true
  previous-version:
    description: 'Previous version released'
    required: false
  new-version:
    description: 'New version to be released'
    required: false
  jira-url:
    description: 'The jira create release url'
    required: false
outputs:
  release-notes:
    description: 'Generated release notes string'
